import { holdings } from "@/utils/data/mockHoldingData";
import { Item } from '@/types/plaid';

const account = {
  accounts: [
    {
      account_id: "Rh7KpM9nQwJRxZ8vLmPqTxwoNz12B4D56hjGt",
      balances: {
        available: 2500.75,
        current: 8500.2,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      holder_category: "personal",
      mask: "1234",
      name: "Robinhood Brokerage",
      official_name: "Robinhood Individual Investing Account",
      subtype: "brokerage",
      type: "investment",
      access_token: "access-production-7b9e2f4d-8c1a-4e5b-a2d3-f6e7890c3d2b",
    },
  ],
  holdings: [
    {
      account_id: "Rh7KpM9nQwJRxZ8vLmPqTxwoNz12B4D56hjGt",
      cost_basis: 150.0,
      institution_price: 165.5,
      institution_price_as_of: "2025-03-21",
      institution_price_datetime: "2025-03-21T16:00:00Z",
      institution_value: 3310.0,
      iso_currency_code: "USD",
      quantity: 20,
      security_id: "AAPL7XPMklt5vwPmDN45t3KAoWAPmjtpaW7DP",
      unofficial_currency_code: null,
    },
    {
      account_id: "Rh7KpM9nQwJRxZ8vLmPqTxwoNz12B4D56hjGt",
      cost_basis: 2800.0,
      institution_price: 290.75,
      institution_price_as_of: "2025-03-21",
      institution_price_datetime: "2025-03-21T16:00:00Z",
      institution_value: 2907.5,
      iso_currency_code: "USD",
      quantity: 10,
      security_id: "TSLAQrXQoqzt5v3bAe8qRt4A7mK7wvZCLEBBJk",
      unofficial_currency_code: null,
    },
    {
      account_id: "Rh7KpM9nQwJRxZ8vLmPqTxwoNz12B4D56hjGt",
      cost_basis: 0.3,
      institution_price: 0.45,
      institution_price_as_of: "2025-03-22",
      institution_price_datetime: "2025-03-22T14:30:00Z",
      institution_value: 2250.0,
      iso_currency_code: "USD",
      quantity: 5000,
      security_id: "DOGE8doZ4lfKNEDe3mPJipLGkaGw3jfPrpxoN",
      unofficial_currency_code: null,
    },
    {
      account_id: "Rh7KpM9nQwJRxZ8vLmPqTxwoNz12B4D56hjGt",
      cost_basis: 32.5,
      institution_price: 30.25,
      institution_price_as_of: "2025-03-21",
      institution_price_datetime: "2025-03-21T16:00:00Z",
      institution_value: 32.5,
      iso_currency_code: "USD",
      quantity: 1.073,
      security_id: "SPY4yz4XQEtwb2YArO7RFMpPDvPxy7FALRyea",
      unofficial_currency_code: null,
    },
  ],
  item: {
    available_products: ["balance", "transactions"],
    billed_products: ["investments"],
    consent_expiration_time: null,
    error: null,
    institution_id: "ins_127001",
    institution_name: "Robinhood",
    item_id: "Rh9KpM9nQwJRxZ8vLmPqTxwoNz23B5D67hjGt",
    update_type: "background",
    webhook: "https://example.com/webhook/robinhood",
    auth_method: "INSTANT_AUTH",
  },
  securities: [
    {
      security_id: "AAPL7XPMklt5vwPmDN45t3KAoWAPmjtpaW7DP",
      name: "Apple Inc.",
      ticker_symbol: "AAPL",
      type: "equity",
      is_cash_equivalent: false,
      close_price: 165.5,
      close_price_as_of: "2025-03-21",
      iso_currency_code: "USD",
      unofficial_currency_code: null,
      cusip: "037833100",
      isin: "US0378331005",
      sedol: null,
      institution_id: null,
      institution_security_id: null,
      proxy_security_id: null,
      market_identifier_code: "XNAS",
      sector: "Technology",
      industry: "Consumer Electronics",
      update_datetime: "2025-03-21T16:00:00Z",
      option_contract: null,
      fixed_income: null,
    },
    {
      security_id: "TSLAQrXQoqzt5v3bAe8qRt4A7mK7wvZCLEBBJk",
      name: "Tesla Inc.",
      ticker_symbol: "TSLA",
      type: "equity",
      is_cash_equivalent: false,
      close_price: 290.75,
      close_price_as_of: "2025-03-21",
      iso_currency_code: "USD",
      unofficial_currency_code: null,
      cusip: "88160R101",
      isin: "US88160R1014",
      sedol: null,
      institution_id: null,
      institution_security_id: null,
      proxy_security_id: null,
      market_identifier_code: "XNAS",
      sector: "Consumer Discretionary",
      industry: "Automotive",
      update_datetime: "2025-03-21T16:00:00Z",
      option_contract: null,
      fixed_income: null,
    },
    {
      security_id: "DOGE8doZ4lfKNEDe3mPJipLGkaGw3jfPrpxoN",
      name: "Dogecoin",
      ticker_symbol: "DOGE",
      type: "cryptocurrency",
      is_cash_equivalent: false,
      close_price: 0.45,
      close_price_as_of: "2025-03-22",
      iso_currency_code: "USD",
      unofficial_currency_code: null,
      cusip: null,
      isin: null,
      sedol: null,
      institution_id: "ins_127001",
      institution_security_id: null,
      proxy_security_id: null,
      market_identifier_code: null,
      sector: null,
      industry: null,
      update_datetime: "2025-03-22T14:30:00Z",
      option_contract: null,
      fixed_income: null,
    },
    {
      security_id: "SPY4yz4XQEtwb2YArO7RFMpPDvPxy7FALRyea",
      name: "SPDR S&P 500 ETF Trust",
      ticker_symbol: "SPY",
      type: "etf",
      is_cash_equivalent: false,
      close_price: 30.25,
      close_price_as_of: "2025-03-21",
      iso_currency_code: "USD",
      unofficial_currency_code: null,
      cusip: "78462F103",
      isin: "US78462F1030",
      sedol: null,
      institution_id: null,
      institution_security_id: null,
      proxy_security_id: null,
      market_identifier_code: "XNAS",
      sector: "Financials",
      industry: "Exchange Traded Funds",
      update_datetime: "2025-03-21T16:00:00Z",
      option_contract: null,
      fixed_income: null,
    },
  ],
  request_id: "RhQwRtYvLmPx9Kp",
  is_investments_fallback_item: false,
};

export const getHoldingsAndSecuritiesMock = async (items: Item[]) => {
  // Get all access tokens in items
  const accessTokens = items.map((item) => item.access_token);

  // Get all accounts associated with the access tokens
  const accounts = accessTokens.filter((account) => accessTokens.includes(account?.accounts?.access_token));

  return {holdings: [], securities: []};
};
